// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/listar-lojas.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/listar-lojas.ts
var listar_lojas_default = defineTool({
  name: "listar_lojas",
  title: "Listar lojas",
  description: "Lista as lojas (unidades) do usu\xE1rio autenticado no Compra360.",
  inputSchema: {
    limite: z.number().int().min(1).max(100).default(50).describe("M\xE1ximo de lojas a retornar.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limite }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("lojas").select("id, nome, nome_fantasia, cnpj, telefone, endereco, created_at").order("created_at", { ascending: true }).limit(limite ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { lojas: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/listar-fornecedores.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var listar_fornecedores_default = defineTool2({
  name: "listar_fornecedores",
  title: "Listar fornecedores",
  description: "Lista os fornecedores cadastrados do usu\xE1rio, com pedido m\xEDnimo e prazo de pagamento.",
  inputSchema: {
    busca: z2.string().trim().min(1).optional().describe("Filtro por parte do nome do fornecedor."),
    limite: z2.number().int().min(1).max(200).default(50).describe("M\xE1ximo de fornecedores a retornar.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ busca, limite }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("fornecedores").select("id, nome, representante, telefone, email, pedido_minimo, prazo_pagamento, observacoes").order("nome", { ascending: true }).limit(limite ?? 50);
    if (busca) query = query.ilike("nome", `%${busca}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { fornecedores: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/listar-cotacoes.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var listar_cotacoes_default = defineTool3({
  name: "listar_cotacoes",
  title: "Listar cota\xE7\xF5es",
  description: "Lista as cota\xE7\xF5es do usu\xE1rio (ativas e finalizadas), com loja, status e prazo de resposta.",
  inputSchema: {
    status: z3.enum(["ativa", "finalizada"]).optional().describe("Filtrar por status da cota\xE7\xE3o."),
    loja_id: z3.string().uuid().optional().describe("Filtrar por loja (unidade)."),
    limite: z3.number().int().min(1).max(50).default(10).describe("M\xE1ximo de cota\xE7\xF5es a retornar.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, loja_id, limite }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("cotacoes").select("id, nome, status, loja_id, prazo_resposta, created_at, finalizada_at, lojas(nome)").order("created_at", { ascending: false }).limit(limite ?? 10);
    if (status) query = query.eq("status", status);
    if (loja_id) query = query.eq("loja_id", loja_id);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { cotacoes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/detalhar-cotacao.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var detalhar_cotacao_default = defineTool4({
  name: "detalhar_cotacao",
  title: "Detalhar cota\xE7\xE3o",
  description: "Retorna os itens de uma cota\xE7\xE3o com quantidades, embalagem e os pre\xE7os recebidos de cada fornecedor, incluindo o menor pre\xE7o por item.",
  inputSchema: {
    cotacao_id: z4.string().uuid().describe("ID da cota\xE7\xE3o (use listar_cotacoes para obter).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ cotacao_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: cotacao, error: cotacaoError } = await supabase.from("cotacoes").select("id, nome, status, loja_id, prazo_resposta, created_at").eq("id", cotacao_id).maybeSingle();
    if (cotacaoError) return { content: [{ type: "text", text: cotacaoError.message }], isError: true };
    if (!cotacao) {
      return { content: [{ type: "text", text: "Cota\xE7\xE3o n\xE3o encontrada." }], isError: true };
    }
    const [{ data: itens, error: itensError }, { data: fornecedores }] = await Promise.all([
      supabase.from("cotacao_produtos").select("id, nome, ean, quantidade, tipo_embalagem, fator_embalagem, precos(preco, fornecedor_id)").eq("cotacao_id", cotacao_id).order("nome", { ascending: true }),
      supabase.from("fornecedores").select("id, nome")
    ]);
    if (itensError) return { content: [{ type: "text", text: itensError.message }], isError: true };
    const nomeFornecedor = new Map((fornecedores ?? []).map((f) => [f.id, f.nome]));
    const resultado = (itens ?? []).map((item) => {
      const precos = (item.precos ?? []).filter((p) => typeof p.preco === "number").map((p) => ({
        fornecedor_id: p.fornecedor_id,
        fornecedor: p.fornecedor_id ? nomeFornecedor.get(p.fornecedor_id) ?? null : null,
        preco: p.preco
      })).sort((a, b) => a.preco - b.preco);
      return {
        id: item.id,
        nome: item.nome,
        ean: item.ean,
        quantidade: item.quantidade,
        embalagem: item.tipo_embalagem,
        fator_embalagem: item.fator_embalagem,
        precos,
        melhor_preco: precos[0] ?? null
      };
    });
    const payload = { cotacao, total_itens: resultado.length, itens: resultado };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/listar-itens-faltantes.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var listar_itens_faltantes_default = defineTool5({
  name: "listar_itens_faltantes",
  title: "Listar itens faltantes",
  description: "Lista os itens de reposi\xE7\xE3o registrados pela equipe da loja (produtos em falta), pendentes ou j\xE1 importados para cota\xE7\xE3o.",
  inputSchema: {
    loja_id: z5.string().uuid().optional().describe("Filtrar por loja (unidade)."),
    apenas_pendentes: z5.boolean().default(true).describe("Se verdadeiro, retorna s\xF3 os itens ainda n\xE3o importados."),
    limite: z5.number().int().min(1).max(200).default(100).describe("M\xE1ximo de itens a retornar.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ loja_id, apenas_pendentes, limite }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("itens_faltantes").select("id, nome, ean, quantidade, embalagem, fator_embalagem, observacao, registrado_por, importado, loja_id, created_at, lojas(nome)").order("created_at", { ascending: false }).limit(limite ?? 100);
    if (loja_id) query = query.eq("loja_id", loja_id);
    if (apenas_pendentes !== false) query = query.eq("importado", false);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { itens: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/registrar-item-faltante.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^3.25.76";
var registrar_item_faltante_default = defineTool6({
  name: "registrar_item_faltante",
  title: "Registrar item faltante",
  description: "Registra um produto em falta na fila de reposi\xE7\xE3o de uma loja, para depois ser importado em uma cota\xE7\xE3o.",
  inputSchema: {
    loja_id: z6.string().uuid().describe("ID da loja (use listar_lojas)."),
    nome: z6.string().trim().min(2).describe("Nome do produto em falta."),
    quantidade: z6.number().int().min(1).default(1).describe("Quantidade necess\xE1ria."),
    embalagem: z6.string().trim().min(1).optional().describe("Embalagem, ex: UN, CX, FD."),
    fator_embalagem: z6.number().int().min(1).optional().describe("Quantas unidades por embalagem."),
    ean: z6.string().trim().optional().describe("C\xF3digo de barras, se conhecido."),
    observacao: z6.string().trim().max(500).optional().describe("Observa\xE7\xE3o livre.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("itens_faltantes").insert({
      loja_id: input.loja_id,
      nome: input.nome,
      quantidade: input.quantidade ?? 1,
      embalagem: input.embalagem ?? null,
      fator_embalagem: input.fator_embalagem ?? null,
      ean: input.ean ?? null,
      observacao: input.observacao ?? null,
      registrado_por: ctx.getUserEmail() ?? "Assistente (MCP)",
      importado: false
    }).select("id, nome, quantidade, embalagem, fator_embalagem, loja_id").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { item: data }
    };
  }
});

// src/lib/mcp/tools/buscar-catalogo.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z7 } from "npm:zod@^3.25.76";
var buscar_catalogo_default = defineTool7({
  name: "buscar_catalogo",
  title: "Buscar no cat\xE1logo",
  description: "Busca produtos no cat\xE1logo mestre do Compra360 por nome ou por c\xF3digo de barras (EAN).",
  inputSchema: {
    termo: z7.string().trim().min(2).describe("Nome do produto ou EAN (s\xF3 d\xEDgitos)."),
    limite: z7.number().int().min(1).max(50).default(20).describe("M\xE1ximo de resultados.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ termo, limite }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const isEan = /^\d+$/.test(termo);
    let query = supabase.from("catalogo_mestre").select("id, nome, ean, categoria, embalagem, fator_embalagem").eq("ativo", true).limit(limite ?? 20);
    query = isEan ? query.or(`ean.ilike.${termo}%,nome.ilike.%${termo}%`) : query.ilike("nome", `%${termo}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { produtos: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "gkokwhkpjfozhtgfcrhz";
var mcp_default = defineMcp({
  name: "compra360",
  title: "Compra360",
  version: "0.1.0",
  instructions: "Ferramentas do Compra360, sistema de cota\xE7\xE3o de compras para supermercados. Use listar_lojas para descobrir as unidades do usu\xE1rio, listar_fornecedores para os fornecedores cadastrados, listar_cotacoes e detalhar_cotacao para analisar pre\xE7os recebidos e o melhor pre\xE7o por item, buscar_catalogo para localizar produtos no cat\xE1logo mestre, e listar_itens_faltantes/registrar_item_faltante para a fila de reposi\xE7\xE3o das lojas. Todas as ferramentas operam apenas nos dados do usu\xE1rio autenticado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    listar_lojas_default,
    listar_fornecedores_default,
    listar_cotacoes_default,
    detalhar_cotacao_default,
    buscar_catalogo_default,
    listar_itens_faltantes_default,
    registrar_item_faltante_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
